'use strict';
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('pipeliner', Object.freeze({
  request: payload => ipcRenderer.invoke('connections:control', payload),
  onStatus: callback => { ipcRenderer.on('connections:status', (_event, value) => callback(value)); },
  workspaceRequest: payload => ipcRenderer.invoke('workspaces:control', payload),
  onWorkspaces: callback => { ipcRenderer.on('workspaces:status', (_event, value) => callback(value)); },
  issueRequest: payload => ipcRenderer.invoke('issues:control', payload),
  onIssues: callback => { ipcRenderer.on('issues:status', (_event, value) => callback(value)); },
  pipelineRequest: payload => ipcRenderer.invoke('pipelines:control', payload),
  onPipelines: callback => { ipcRenderer.on('pipelines:status', (_event, value) => callback(value)); },
  developmentRequest: payload => ipcRenderer.invoke('development:control', payload),
  onDevelopment: callback => { ipcRenderer.on('development:status', (_event, value) => callback(value)); },
  schedulingRequest: payload => ipcRenderer.invoke('scheduling:control', payload),
  onScheduling: callback => { ipcRenderer.on('scheduling:status', (_event, value) => callback(value)); },
  backgroundRequest: payload => ipcRenderer.invoke('background:control', payload),
  onBackground: callback => { ipcRenderer.on('background:status', (_event, value) => callback(value)); },
  skillRequest: payload => ipcRenderer.invoke('skills:control', payload),
  onSkills: callback => { ipcRenderer.on('skills:status', (_event, value) => callback(value)); },
  toolRequest: payload => ipcRenderer.invoke('tools:control', payload),
  onTools: callback => { ipcRenderer.on('tools:status', (_event, value) => callback(value)); },
  privacyRequest: payload => ipcRenderer.invoke('privacy:control', payload),
  onPrivacy: callback => { ipcRenderer.on('privacy:status', (_event, value) => callback(value)); },
  appearanceRequest: payload => ipcRenderer.invoke('appearance:control', payload),
  onAppearance: callback => { ipcRenderer.on('appearance:status', (_event, value) => callback(value)); },
  deliveryRequest: payload => ipcRenderer.invoke('delivery:control', payload),
  onDelivery: callback => { ipcRenderer.on('delivery:status', (_event, value) => callback(value)); },
}));
